name = "library-notes-storage"
main = "worker.js"
compatibility_date = "2026-08-01"

# After creating the namespace with:
#   wrangler kv namespace create LIBRARY_NOTES_KV
# paste the returned "id" below.
[[kv_namespaces]]
binding = "LIBRARY_NOTES_KV"
id = "1d173e85a1a64c28a394de2844be6c34"
