'use strict';
const KEY='app-studio-marketplace-drafts-v1';
const draftsEl=document.getElementById('drafts');
let drafts=JSON.parse(localStorage.getItem(KEY)||'[]');
function save(){localStorage.setItem(KEY,JSON.stringify(drafts));render()}
function card(d){const el=document.createElement('article');el.className='draft';el.innerHTML=`<p class="eyebrow">${d.type==='client'?'고객 요청':'개발자 프로필'}</p><h3></h3><p class="meta"></p><p class="body"></p><div class="draft-actions"><button type="button" data-action="edit">수정</button><button type="button" data-action="delete">삭제</button></div>`;el.querySelector('h3').textContent=d.title||d.name;el.querySelector('.meta').textContent=d.type==='client'?`${d.platform} · 예산 ${Number(d.budget||0).toLocaleString()}원 · ${d.status||'초안'}`:`${d.platform} · ${Number(d.price||0).toLocaleString()}원부터`;el.querySelector('.body').textContent=d.need||`${d.skills}${d.url?' · '+d.url:''}`;el.querySelector('[data-action="delete"]').onclick=()=>{drafts=drafts.filter(x=>x.id!==d.id);save()};el.querySelector('[data-action="edit"]').onclick=()=>{const form=document.getElementById(d.type==='client'?'client-form':'dev-form');Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});drafts=drafts.filter(x=>x.id!==d.id);save();form.scrollIntoView({behavior:'smooth',block:'center'})};return el}
function render(){draftsEl.replaceChildren(...(drafts.length?drafts.map(card):[Object.assign(document.createElement('p'),{className:'empty',textContent:'아직 초안이 없습니다. 위에서 하나 만들어보세요.'})]))}
function bind(form,type){form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d={id:crypto.randomUUID(),type,...Object.fromEntries(new FormData(form)),status:type==='client'?'초안':'등록 초안',createdAt:new Date().toISOString()};drafts.unshift(d);save();form.reset();const out=document.getElementById(type==='client'?'client-output':'dev-output');out.hidden=false;out.textContent='초안을 저장했어요. 이 데이터는 현재 브라우저 안에만 있습니다.'})}
bind(document.getElementById('client-form'),'client');bind(document.getElementById('dev-form'),'developer');document.getElementById('clear').addEventListener('click',()=>{drafts=[];save()});render();
document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,scope:'local-browser-only',drafts},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='app-studio-marketplace-drafts.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('demo-status').onclick=()=>{const request=drafts.find(d=>d.type==='client');const out=document.getElementById('status-output');if(!request){out.textContent='고객 요청 초안을 먼저 저장해 주세요.';return}request.status='접수 준비';save();out.textContent='최근 고객 요청을 “접수 준비”로 표시했습니다. 실제 전송은 서버 연결 후에만 가능합니다.'};
